POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstname": "Tomy",
    "lastname": "Visou",
    "email": "tomyvisou@email.com",
    "city": "Paris",
    "language": "fr",
    "password": "aeezrezrezrez"
}

###