POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "johndoe@email.com",
    "city": "Lille",
    "language": "islandais",
    "password": "azerty"
}

###